# Generated by Django 5.1.2 on 2024-11-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='discount_upto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='catagory',
            name='short_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
