# Generated by Django 5.1.2 on 2024-11-15 06:54

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_catagory_discount_upto_catagory_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='fourth_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='second_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='third_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(max_length=150),
        ),
    ]
