# Generated by Django 5.1.2 on 2024-11-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_list_price_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.catagory'),
        ),
    ]
