# Generated by Django 5.1.2 on 2024-12-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_slide1_slide2_slide3_slide5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slide5',
            new_name='slide4',
        ),
    ]
